### ISSUE TITLE
Update Curral/Piquete - BUG

### ISSUE THREAD

**Issue by GabrielSanga** [GabrielSanga/Syscomn-Back#1]
# Update Curral Piquete

Ao realizar uma alteração no curral/piquete a aplicação está emitindo uma mensagem de erro (BAD REQUEST), não realizando a operação de Update.

![Issues1](https://user-images.githubusercontent.com/89952288/164793897-4e892e25-e5aa-41e4-8202-a13282c388c8.png)

**Comment by GallegoPolo** [comment]
Correção realizada.
-A alteração realizada foi alterar as rotinas para não mais utilizar o enum, e sim um simples gravação na base de dados, onde foi ajustado as descrições por um método no TS.
